### ISSUE TITLE
can this tools used to private account ?

### ISSUE THREAD

**Issue by firdausakbarr** [Dinoosauro/tiktok-to-ytdlp#1]

**Comment by Dinoosauro** [comment]
Hi! You can use this script for private accounts that you follow (the TikTok page must display the user's videos, since data is fetched directly from the DOM). Then I think you have to pass cookies to yt-dlp so that also follower-only videos can be downloaded. However, if you don't follow that private account, you won't be able to fetch their TikToks with this script
