### ISSUE TITLE
How to get link download without logo

### ISSUE THREAD

**Issue by trithucxx** [Dinoosauro/tiktok-to-ytdlp#13]
I launched and it worked, but non logo is perfect! So, could you improve it?

**Comment by Dinoosauro** [comment]
Hi! The download of videos is done directly by yt-dlp. The only thing this script does is collecting the videos from the TikTok user/sound/liked videos etc. page and putting them in a file, so that yt-dlp can download them.
I read a few days ago that TikTok has restricted the usage of their APIs, and therefore projects like yt-dlp had to update their code to circumvent those. It seems that yt-dlp has found a solution (the issue that tracked the error has been closed: https://github.com/yt-dlp/yt-dlp/issues/9506), so maybe with the next release you should be able to download videos without the TikTok watermark. Until a few days ago yt-dlp always downloaded the video without the watermark – so I think that it's related to that issue

**Comment by trithucxx** [comment]
> Hi! The download of videos is done directly by yt-dlp. The only thing this script does is collecting the videos from the TikTok user/sound/liked videos etc. page and putting them in a file, so that yt-dlp can download them. I read a few days ago that TikTok has restricted the usage of their APIs, and therefore projects like yt-dlp had to update their code to circumvent those. It seems that yt-dlp has found a solution (the issue that tracked the error has been closed: [yt-dlp/yt-dlp#9506](https://github.com/yt-dlp/yt-dlp/issues/9506)), so maybe with the next release you should be able to download videos without the TikTok watermark. Until a few days ago yt-dlp always downloaded the video without the watermark, so I think that it's related to that issue

yeah, thanks a lot. It's worked

**Comment by Dinoosauro** [comment]
Glad I helped!
