### ISSUE TITLE
Can we migrate this script to node script

### ISSUE THREAD

**Issue by cinohub** [Dinoosauro/tiktok-to-ytdlp#9]
Hi there,
Thank for your awsome work.

This script only run in console window, so that we must open browser to run script.
Now Can we migrate this to node js framework. I mean we just input the tiktok user id, node js will convert this script then run all thing to fetch videos then download it.
That's my idea.

Thank again for your script

**Comment by Dinoosauro** [comment]
Hi, thanks a lot for the idea! 
Currently this script relies on video extraction from the DOM, so a browser is necessary. However, I think that it's possible to automate this process by using something like Selenium or Puppeteer: a browser controlled by a Node script will open the page, then the TikTok script will be injected to fetch the video URLs, and then the Node script will manage to download everything. I'll try to do something like this in these days

**Comment by Dinoosauro** [comment]
I've created a Node.JS module that can be imported to do this. Puppeteer will be used, so the webpage will still be rendered, but it could be useful for automation.

The module gives only an array of Video URLs, adapting them to be downloaded with yt-dlp could be done by calling the yt-dlp process for each video. I would do something like this:

```
const script = require("./script")("https://www.tiktok.com/@mrbeast");

let webpage = await script.create();
let videoArray = await webpage.start();
videoArray.forEach((video) => {
require("child_process").execSync(`yt-dlp ${video}`);
})
```

If you want to take a look to the module, I've uploaded in another repository, so that maybe in the following days I can upload it to NPM and simplify both the download and the eventual updates: https://github.com/Dinoosauro/node-tiktok-to-ytdlp/tree/main
